title = "Nicolas A. H. Lara"
theme = "not-much"
languageCode = "en-us"
baseURL = "https://www.nicolasahlara.com"

[markup]
  [markup.highlight]
    style = 'dracula'
  [markup.goldmark]
    [markup.goldmark.renderer]
      unsafe = true


[params]
theme = "light"
palette = "cork_forest"
showThemeNotice = true

# Navigation
[menu]
  [[menu.main]]
    identifier = "home"
    name = "home"
    title = "home"
    url = "/"
    weight = 1

  [[menu.main]]
    identifier = "resume"
    name = "resume"
    title = "resume"
    url = "/resume/resume"
    weight = 2
 
  [[menu.main]]
    identifier = "posts"
    name = "blog"
    title = "posts"
    url = "/posts"
    weight = 3

  [[menu.main]]
    identifier = "cookbook"
    name = "cookbook"
    title = "cookbook"
    url = "/cookbook/cookbook"
    weight = 3
 
  
  [[menu.main]]
    identifier = "github"
    name = "github"
    title = "GitHub"
    url = "https://github.com/nicohlara"
    weight = 4

  [[menu.main]]
    identifier = "linkedin"
    name = "linkedin"
    title = "LinkedIn"
    url = "https://www.linkedin.com/in/nicolasahlara/"
    weight = 5

[taxonomies]
tag = "tags"
